apiVersion: v1
kind: Pod
metadata:
spec:
  serviceAccount: aplazame-frontdeployer
  securityContext:
    fsGroup: 1000
  containers:
  - name: node
    image: 666356151544.dkr.ecr.eu-central-1.amazonaws.com/tools/node:14.17.3
    imagePullPolicy: Always
    command:
    - cat
    tty: true
    resources:
      requests:
        memory: 4Gi
        cpu: 2
      limits:
        memory: 4Gi
        cpu: 2